<a href="https://colab.research.google.com/github/rajasreekalli/Data-Visualization/blob/main/Logistic_Regression_Core.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [196]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, \
f1_score, classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

In [197]:
df = pd.read_csv('/content/drive/MyDrive/wine.data')
df

1  14.23  1.71  2.43  15.6  127  ...   .28  2.29   5.64  1.04  3.92  1065
0    1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
1    1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
2    1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
3    1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
4    1  14.20  1.76  2.45  15.2  112  ...  0.34  1.97   6.75  1.05  2.85  1450
..  ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
172  3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
173  3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
174  3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
175  3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
176  3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[177 rows x 14 columns]

In [198]:
import pandas as pd
# list the names of the columns from the wine.name file 
col_names = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols',
'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins','Color intensity', 'Hue', 'OD280/OD315 of diluted wines','Proline']
# define the url and make sure to specify the wine.data file at the end
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
# read in the file from the url and include the list of names as your column names
df = pd.read_csv(url, header = None, names = col_names)
df

Class label  Alcohol  ...  OD280/OD315 of diluted wines  Proline
0              1    14.23  ...                          3.92     1065
1              1    13.20  ...                          3.40     1050
2              1    13.16  ...                          3.17     1185
3              1    14.37  ...                          3.45     1480
4              1    13.24  ...                          2.93      735
..           ...      ...  ...                           ...      ...
173            3    13.71  ...                          1.74      740
174            3    13.40  ...                          1.56      750
175            3    13.27  ...                          1.56      835
176            3    13.17  ...                          1.62      840
177            3    14.13  ...                          1.60      560

[178 rows x 14 columns]

In [199]:
print('Missing data:\n', df.isna().sum())
print('\n')
print('Duplicates:', df.duplicated().sum())

Missing data:
 Class label                     0
Alcohol                         0
Malic acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
dtype: int64


Duplicates: 0


In [200]:
logreg_params = {
    'penalty': ['l2',],
               'C': [1, 2, 3, 4, 5, 10, 20, 50, 100, 500, 1000],
               'dual': [False],
               'multi_class': ['ovr']
               }
model = LogisticRegression(random_state = 42)
grid = GridSearchCV(model, logreg_params)

In [203]:
grid.best_params_

{'C': 2, 'dual': False, 'multi_class': 'ovr', 'penalty': 'l2'}

In [220]:
model = LogisticRegression(C = 1, dual = False, multi_class = 'ovr', penalty= 'l2', random_state = 42)
ovo = OneVsOneClassifier(model)
ovo.fit(X_train, y_train)
ovo_y_pred = ovo.predict(X_test)
ovo.score(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9849624060150376

In [206]:
# split data into train and test sets...notice that stratify = y will give the same proportion of yes/no in our train and test sets
X = df.drop(columns = ['Proline', 'Class label'])
y = df['Class label']

In [207]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, stratify = y)

In [208]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [209]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [210]:
knn = KNeighborsClassifier()

knn.fit(X_train_scaled, y_train)

train_preds = knn.predict(X_train_scaled)
test_preds = knn.predict(X_test_scaled)

In [211]:
def evaluate_classification(y_true, y_test, average=None):
  accuracy = accuracy_score(y_true, y_test)
  recall = recall_score(y_true, y_test, average=average)
  precision = precision_score(y_true, y_test, average=average)
  f1 = f1_score(y_true, y_test, average=average)

  print(f'Accuracy: {accuracy} \nRecall: {recall} \nPrecision: {precision} \nF1 Score: {f1}')

In [212]:
print('Training Metrics\n')
evaluate_classification(y_train, train_preds, average='macro')
print('\n')

print('Testing Metrics\n')
evaluate_classification(y_test, test_preds, average='macro')

Training Metrics

Accuracy: 0.9699248120300752 
Recall: 0.9748427672955975 
Precision: 0.9679633867276888 
F1 Score: 0.970511688158747


Testing Metrics

Accuracy: 0.9555555555555556 
Recall: 0.9629629629629629 
Precision: 0.9535256410256411 
F1 Score: 0.9563061353573689


In [213]:
knn = KNeighborsClassifier(n_neighbors=5)

In [214]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')


In [216]:
predictions = knn.predict(X_test)
predictions

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 2, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 3, 3, 2, 3, 2, 2, 2, 1,
       3])

In [217]:
score = knn.score(X_test, y_test)
score

0.8444444444444444

In [222]:
print('Classification Report for Training Set')
train_report = classification_report(y_train, train_preds)
print(train_report)

print('Confusion Matrix for Training Set')
train_conf_mat = confusion_matrix(y_train, train_preds)
print(train_conf_mat)

print('\n\n')

print('Classification Report for Testing Set')

test_report = classification_report(y_test, test_preds)
print(test_report)

print('Confusion Matrix for Testing Set')
test_conf_mat = confusion_matrix(y_test, test_preds)
print(test_conf_mat)


Classification Report for Training Set
              precision    recall  f1-score   support

           1       0.96      1.00      0.98        44
           2       1.00      0.92      0.96        53
           3       0.95      1.00      0.97        36

    accuracy                           0.97       133
   macro avg       0.97      0.97      0.97       133
weighted avg       0.97      0.97      0.97       133

Confusion Matrix for Training Set
[[44  0  0]
 [ 2 49  2]
 [ 0  0 36]]



Classification Report for Testing Set
              precision    recall  f1-score   support

           1       0.94      1.00      0.97        15
           2       1.00      0.89      0.94        18
           3       0.92      1.00      0.96        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Confusion Matrix for Testing Set
[[15  0  0]
 [ 1 16  1]
 [ 0  0 12]]


In [223]:
ovr = OneVsRestClassifier(model)
ovr.fit(X_train, y_train)
ovr_y_pred = ovo.predict(X_test)
ovr.score(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9774436090225563