<a href="https://colab.research.google.com/github/rajasreekalli/Data-Visualization/blob/main/Logistic%2C_Random_forest%2C_or_KNN%3F_(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, \
f1_score, classification_report, confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

In [2]:
df = pd.read_csv('/content/drive/MyDrive/wine.data')
df

1  14.23  1.71  2.43  15.6  127  ...   .28  2.29   5.64  1.04  3.92  1065
0    1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
1    1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
2    1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
3    1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
4    1  14.20  1.76  2.45  15.2  112  ...  0.34  1.97   6.75  1.05  2.85  1450
..  ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
172  3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
173  3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
174  3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
175  3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
176  3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[177 rows x 14 columns]

In [3]:
import pandas as pd
# list the names of the columns from the wine.name file 
col_names = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols',
'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins','Color intensity', 'Hue', 'OD280/OD315 of diluted wines','Proline']
# define the url and make sure to specify the wine.data file at the end
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
# read in the file from the url and include the list of names as your column names
df = pd.read_csv(url, header = None, names = col_names)
df

Class label  Alcohol  ...  OD280/OD315 of diluted wines  Proline
0              1    14.23  ...                          3.92     1065
1              1    13.20  ...                          3.40     1050
2              1    13.16  ...                          3.17     1185
3              1    14.37  ...                          3.45     1480
4              1    13.24  ...                          2.93      735
..           ...      ...  ...                           ...      ...
173            3    13.71  ...                          1.74      740
174            3    13.40  ...                          1.56      750
175            3    13.27  ...                          1.56      835
176            3    13.17  ...                          1.62      840
177            3    14.13  ...                          1.60      560

[178 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Class label                   178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

In [5]:
print('Missing data:\n', df.isna().sum())
print('\n')
print('Duplicates:', df.duplicated().sum())

Missing data:
 Class label                     0
Alcohol                         0
Malic acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
dtype: int64


Duplicates: 0


In [6]:
X = df.drop(columns = ['Proline', 'Class label'])
y = df['Class label']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [8]:
logreg_params = {
    'penalty': ['l2',],
               'C': [1, 2, 3, 4, 5, 10, 20, 50, 100, 500, 1000],
               'dual': [False],
               'multi_class': ['ovr']
               }
model = LogisticRegression(random_state = 42)
grid = GridSearchCV(model, logreg_params)

In [31]:
grid.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


GridSearchCV(estimator=LogisticRegression(random_state=42),
             param_grid={'C': [1, 2, 3, 4, 5, 10, 20, 50, 100, 500, 1000],
                         'dual': [False], 'multi_class': ['ovr'],
                         'penalty': ['l2']})

In [32]:
best_lr = grid.best_estimator_

lr_train_preds = best_lr.predict(X_train)
lr_test_preds = best_lr.predict(X_test)
print('Best LR Model Train Metrics')
print(classification_report(y_train, lr_train_preds))
print('\nBest LR Model Test Metrics')
print(classification_report(y_test, lr_test_preds))

print('Classification Report for LR Training Set')
lr_train_report = classification_report(y_train, lr_train_preds)
print(lr_train_report)

print('Confusion Matrix for LR Training Set')
lr_train_conf_mat = confusion_matrix(y_train, lr_train_preds)
print(lr_train_conf_mat)

print('\n\n')

print('Classification Report for LR Testing Set')

lr_test_report = classification_report(y_test, lr_test_preds)
print(lr_test_report)

print('Confusion Matrix for LR Testing Set')
lr_test_conf_mat = confusion_matrix(y_test, lr_test_preds)
print(lr_test_conf_mat)

Best LR Model Train Metrics
              precision    recall  f1-score   support

           1       0.98      0.93      0.95        44
           2       0.94      0.94      0.94        53
           3       0.95      1.00      0.97        36

    accuracy                           0.95       133
   macro avg       0.96      0.96      0.96       133
weighted avg       0.96      0.95      0.95       133


Best LR Model Test Metrics
              precision    recall  f1-score   support

           1       0.79      1.00      0.88        15
           2       0.93      0.78      0.85        18
           3       1.00      0.92      0.96        12

    accuracy                           0.89        45
   macro avg       0.91      0.90      0.90        45
weighted avg       0.90      0.89      0.89        45

Classification Report for LR Training Set
              precision    recall  f1-score   support

           1       0.98      0.93      0.95        44
           2       0.94      0.

In [10]:
model = LogisticRegression(C = 1, dual = False, multi_class = 'ovr', penalty= 'l2', random_state = 42)
ovo = OneVsOneClassifier(model)
ovo.fit(X_train, y_train)
ovo_y_pred = ovo.predict(X_test)
ovo.score(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.9624060150375939

In [11]:
scaler = StandardScaler()
knn = KNeighborsClassifier()

knn_pipe = make_pipeline(scaler, knn)

knn_pipe.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier())])

In [12]:
train_preds = knn_pipe.predict(X_train)
test_preds = knn_pipe.predict(X_test)

print('train accuracy:', accuracy_score(y_train, train_preds))
print('\n')
print('test accuracy:', accuracy_score(y_test, test_preds))

train accuracy: 0.9774436090225563


test accuracy: 0.9111111111111111


In [16]:
logreg_params = {
    'penalty': ['l2',],
               'C': [1, 2, 3, 4, 5, 10, 20, 50, 100, 500, 1000],
               'dual': [False],
               'multi_class': ['ovr']
               }


In [17]:
params = {'kneighborsclassifier__n_neighbors': range(1,20),
          'kneighborsclassifier__weights': ['uniform','distance'],
          'kneighborsclassifier__p': [2,3,4]}

In [18]:
knn_grid = GridSearchCV(knn_pipe, params)

knn_grid.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('kneighborsclassifier',
                                        KNeighborsClassifier())]),
             param_grid={'kneighborsclassifier__n_neighbors': range(1, 20),
                         'kneighborsclassifier__p': [2, 3, 4],
                         'kneighborsclassifier__weights': ['uniform',
                                                           'distance']})

In [19]:
knn_grid.best_params_

{'kneighborsclassifier__n_neighbors': 4,
 'kneighborsclassifier__p': 2,
 'kneighborsclassifier__weights': 'distance'}

In [20]:
best_knn = knn_grid.best_estimator_

In [21]:
train_preds = best_knn.predict(X_train)
test_preds = best_knn.predict(X_test)
print('Best Model Train Metrics')
print(classification_report(y_train, train_preds))
print('\nBest Model Test Metrics')
print(classification_report(y_test, test_preds))

Best Model Train Metrics
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        44
           2       1.00      1.00      1.00        53
           3       1.00      1.00      1.00        36

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133


Best Model Test Metrics
              precision    recall  f1-score   support

           1       0.88      0.93      0.90        15
           2       0.94      0.83      0.88        18
           3       0.92      1.00      0.96        12

    accuracy                           0.91        45
   macro avg       0.91      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45



In [22]:
print('Classification Report for Training Set')
train_report = classification_report(y_train, train_preds)
print(train_report)

print('Confusion Matrix for Training Set')
train_conf_mat = confusion_matrix(y_train, train_preds)
print(train_conf_mat)

print('\n\n')

print('Classification Report for Testing Set')

test_report = classification_report(y_test, test_preds)
print(test_report)

print('Confusion Matrix for Testing Set')
test_conf_mat = confusion_matrix(y_test, test_preds)
print(test_conf_mat)

Classification Report for Training Set
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        44
           2       1.00      1.00      1.00        53
           3       1.00      1.00      1.00        36

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

Confusion Matrix for Training Set
[[44  0  0]
 [ 0 53  0]
 [ 0  0 36]]



Classification Report for Testing Set
              precision    recall  f1-score   support

           1       0.88      0.93      0.90        15
           2       0.94      0.83      0.88        18
           3       0.92      1.00      0.96        12

    accuracy                           0.91        45
   macro avg       0.91      0.92      0.92        45
weighted avg       0.91      0.91      0.91        45

Confusion Matrix for Testing Set
[[14  1  0]
 [ 2 15  1]
 [ 0  0 12]]


In [23]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf_params = {
              'n_estimators': [10, 100, 300],
              'max_depth': range(2,15),
              'min_samples_split': [2, 3, 4, 5]
              }
rf = RandomForestClassifier(random_state = 42)
rf_grid = GridSearchCV(rf, rf_params)

In [46]:
rf_grid.fit(X_train, y_train)

GridSearchCV(estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': range(2, 15),
                         'min_samples_split': [2, 3, 4, 5],
                         'n_estimators': [10, 100, 300]})

In [47]:
rf_grid.best_params_

{'max_depth': 4, 'min_samples_split': 2, 'n_estimators': 300}

In [48]:
best_rf = rf_grid.best_estimator_

In [49]:
train_preds = best_rf.predict(X_train)
test_preds = best_rf.predict(X_test)
print('Best Model Train Metrics')
print(classification_report(y_train, train_preds))
print('\nBest Model Test Metrics')
print(classification_report(y_test, test_preds))

Best Model Train Metrics
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        44
           2       1.00      1.00      1.00        53
           3       1.00      1.00      1.00        36

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133


Best Model Test Metrics
              precision    recall  f1-score   support

           1       0.88      1.00      0.94        15
           2       1.00      0.89      0.94        18
           3       1.00      1.00      1.00        12

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [50]:
print('Classification Report for Training Set')
train_report = classification_report(y_train, train_preds)
print(train_report)

print('Confusion Matrix for Training Set')
train_conf_mat = confusion_matrix(y_train, train_preds)
print(train_conf_mat)

print('\n\n')

print('Classification Report for Testing Set')

test_report = classification_report(y_test, test_preds)
print(test_report)

print('Confusion Matrix for Testing Set')
test_conf_mat = confusion_matrix(y_test, test_preds)
print(test_conf_mat)

Classification Report for Training Set
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        44
           2       1.00      1.00      1.00        53
           3       1.00      1.00      1.00        36

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

Confusion Matrix for Training Set
[[44  0  0]
 [ 0 53  0]
 [ 0  0 36]]



Classification Report for Testing Set
              precision    recall  f1-score   support

           1       0.88      1.00      0.94        15
           2       1.00      0.89      0.94        18
           3       1.00      1.00      1.00        12

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Confusion Matrix for Testing Set
[[15  0  0]
 [ 2 16  0]
 [ 0  0 12]]
